name = "field-manager"
main = "src/index.ts"
compatibility_date = "2023-02-02"

kv_namespaces = [
  { binding = "NAMESPACE_DATING_FIELDS", id = "5ed9bd161ad94728989537ab31d16862" },
  { binding = "NAMESPACE_DATING_FIELD_OPTIONS", id = "15943283cb5a429a86b05650f0b4ab3d"}
]

[env.stg]
name = "field-manager-stg"

[env.prd]
name = "field-manager"

[vars]
# The necessary secrets are:
# - 
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these
ENVIRONMENT = "prd"

[env.stg.vars]
ENVIRONMENT = "stg"

[env.prd.vars]
ENVIRONMENT = "prd"
