import { DashboardItem } from '../../../types/dashboard';

export const testItems: DashboardItem[] = [
  {
    label: 'ClickUp',
    url: 'https://app.clickup.com',
    description: 'Project management',
    section: 'general',
  },
  {
    label: 'Slack',
    url: 'https://butterflies-network.slack.com/',
    description: 'Team communication',
    section: 'general',
  },
  {
    label: 'Dating Web App',
    url: 'https://dating.aerilym.com/',
    icon: 'cloudflare',
    description: 'Web app',
    section: 'general',
  },
  {
    label: 'App Repo',
    url: 'https://github.com/aerilym/dating',
    description: 'Source code',
    section: 'development',
  },
  {
    label: 'Supabase',
    url: 'https://app.supabase.com/project/btueksreggheiyvqbbdx',
    description: 'Database',
    section: 'development',
  },
  {
    label: 'Cloudflare',
    url: 'https://dash.cloudflare.com/809c3cfa8c49d62465a26b07b2e87ee6',
    description: 'Web hosting',
    section: 'development',
  },
  {
    label: 'Cloudflare Workers',
    url: 'https://dash.cloudflare.com/809c3cfa8c49d62465a26b07b2e87ee6/workers/overview',
    description: 'Serverless functions',
    section: 'development',
    expanded: true,
  },
  {
    label: 'Cloudflare Pages',
    url: 'https://dash.cloudflare.com/809c3cfa8c49d62465a26b07b2e87ee6/pages',
    description: 'Web hosting',
    section: 'development',
    expanded: true,
  },
  {
    label: 'Figma',
    url: 'https://www.figma.com/files/team/1155834753303918091',
    description: 'Figma',
    section: 'design',
  },
  {
    label: 'Miro',
    url: 'https://miro.com/app/dashboard/',
    description: 'Miro',
    section: 'design',
  },
  {
    label: 'Design Board',
    url: 'https://miro.com/app/board/uXjVPaTIfGM=/',
    description: 'Design Board',
    section: 'design',
    expanded: true,
  },
  {
    label: 'Vision Board',
    url: 'https://miro.com/app/board/uXjVPZw1JnU=/',
    description: 'Vision Board',
    section: 'design',
    expanded: true,
  },
  {
    label: 'Admin Documents',
    url: 'https://app.clickup.com/36895771/v/dc/135z0v-622',
    description: '',
    section: 'general',
    expanded: true,
  },
  {
    label: 'Technical Documents',
    url: 'https://app.clickup.com/36895771/v/dc/135z0v-602',
    description: '',
    section: 'development',
    expanded: true,
  },
  {
    label: 'Application Wiki',
    url: 'https://app.clickup.com/36895771/v/dc/135z0v-602/135z0v-1762',
    description: 'Application Wiki',
    section: 'development',
    expanded: true,
  },
  {
    label: 'Field Manager',
    url: 'https://tools.dating.aerilym.com/',
    description: 'Field Manager',
    section: 'tool',
    expanded: true,
  },
  {
    label: 'Ideas Board',
    url: 'https://app.clickup.com/36895771/v/l/135z0v-842',
    description: 'Ideas Board',
    section: 'general',
    expanded: true,
  },
];
